### ISSUE TITLE
error: cpuid.h: No such file or directory

### ISSUE THREAD

**Issue by ryandesign** [google/leveldb#560]
leveldb 1.20 fails to build on Mac OS X Snow Leopard v10.6:

```
/usr/bin/g++-4.2 -Os -arch i386 -I. -I./include -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -DSNAPPY -DNDEBUG -fPIC -msse4.2 -DLEVELDB_PLATFORM_POSIX_SSE -c port/port_posix_sse.cc -o out-shared/port/port_posix_sse.o
port/port_posix_sse.cc:22:19: error: cpuid.h: No such file or directory
/usr/bin/g++-4.2 -Os -arch i386 -I. -I./include -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -DSNAPPY -DNDEBUG -c util/testutil.cc -o out-static/util/testutil.o
/usr/bin/g++-4.2 -Os -arch i386 -I. -I./include -DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -DSNAPPY -DNDEBUG -c db/builder.cc -o out-static/db/builder.o
port/port_posix_sse.cc: In function ‘bool leveldb::port::HaveSSE42()’:
port/port_posix_sse.cc:58: error: ‘__get_cpuid’ was not declared in this scope
make: *** [out-shared/port/port_posix_sse.o] Error 1
make: *** Waiting for unfinished jobs....
```

Here is a [build log from MacPorts](https://build.macports.org/builders/ports-10.6_i386_legacy-builder/builds/38199/steps/install-port/logs/stdio).

This is a new problem for 1.20. 1.19 didn't have this problem.

1.20 builds fine on OS X Lion v10.7 and later.

**Comment by pwnall** [comment]
Can you try again with the master branch?

We removed `port_posix_sse.cc` and now LevelDB detects and uses [google/crc32c](https://github.com/google/crc32c) for hardware-accelerated CRC32C computation. You should be able to build LevelDB, but you won't be able to take advantage of the faster CRC32C.

General remark: MacOS 10.6 is fairly old, and we don't support it. Even if we wanted to, we couldn't guarantee support for anything older than what Travis CI supports (10.10 at the moment). The next LevelDB release (1.21) will require C++11 support, and I'm not sure that the 10.6 toolchain has that. You might be stuck on LevelDB 1.19 if you absolutely need to run MacOS 10.6.

**Comment by ryandesign** [comment]
> Can you try again with the master branch?
> 
> We removed port_posix_sse.cc and now LevelDB detects and uses google/crc32c for hardware-accelerated CRC32C computation. You should be able to build LevelDB, but you won't be able to take advantage of the faster CRC32C.

Thanks, I'll try it.

> General remark: MacOS 10.6 is fairly old, and we don't support it. Even if we wanted to, we couldn't guarantee support for anything older than what Travis CI supports (10.10 at the moment). The next LevelDB release (1.21) will require C++11 support, and I'm not sure that the 10.6 toolchain has that. You might be stuck on LevelDB 1.19 if you absolutely need to run MacOS 10.6.

Absolutely, 10.6 is old. MacPorts runs on 10.4 and later and we have automated build machines for 10.5 and later, and it was there that I noticed the failure. As manager of MacPorts, I try to keep an eye on the automated build system and fix or report build failures I see. MacPorts contains C++11 toolchains for older systems that work on 10.5 and later.

**Comment by pwnall** [comment]
Thank you for explaining the context behind the bug!

MacPorts' support for older versions and build infrastructure is impressive. Sorry I can't provide the same guarantees here.

I'm going to close this issue, since the problem it mentions shouldn't occur on master. Please feel free to comment on this issue if this problem somehow still occurs and/or open new issues.
