### ISSUE TITLE
fails to build leveldb-1.7.0 on AIX6.1 

### ISSUE THREAD

**Issue by shaolila** [google/leveldb#326]
hi,everyone
I have downloaded leveldb-1.7.0-4.fc18.src.rpm ,and want use this rpm on AIX6.1,when I execute the command "rpm --rebuild --clean leveldb-1.7.0-4.fc18.src.rpm" ,I got the files :BUILD RPMS SOURCES SPECS SRPMS

bash-4.3# ls SPECS/
leveldb.spec

bash-4.3# ls SOURCES/
leveldb-0001-Initial-commit-of-the-autotools-stuff.patch

leveldb-0002-Add-memory-barrier-on-PowerPC.patch leveldb-1.7.0.tar.gz
leveldb-0003-bloom_test-failure-on-big-endian-archs.patch

leveldb-0004-leveldbjni.patch

and got errors:
checking for ppc-ibm-aix6.1-g++... no
checking for ppc-ibm-aix6.1-c++... no
checking for ppc-ibm-aix6.1-gpp... no
checking for ppc-ibm-aix6.1-aCC... no
checking for ppc-ibm-aix6.1-CC... no
checking for ppc-ibm-aix6.1-cxx... no
checking for ppc-ibm-aix6.1-cc++... no
checking for ppc-ibm-aix6.1-cl.exe... no
checking for ppc-ibm-aix6.1-FCC... no
checking for ppc-ibm-aix6.1-KCC... no
checking for ppc-ibm-aix6.1-RCC... no
checking for ppc-ibm-aix6.1-xlC_r... no
checking for ppc-ibm-aix6.1-xlC... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking how to print strings... print -r
checking for ppc-ibm-aix6.1-gcc... no
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786432
checking how to convert powerpc-ibm-aix6.1 file names to powerpc-ibm-aix6.1 format... func_convert_file_noop
checking how to convert powerpc-ibm-aix6.1 file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for ppc-ibm-aix6.1-objdump... no
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for ppc-ibm-aix6.1-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... print -r --
checking for ppc-ibm-aix6.1-ar... /usr/bin/ar
checking for archiver @FILE support... no
checking for ppc-ibm-aix6.1-strip... no
checking for strip... strip
checking for ppc-ibm-aix6.1-ranlib... no
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for ppc-ibm-aix6.1-mt... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... rm: conftest: No such file or directory yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... aix6.1 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... no
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... rm: conftest: No such file or directory yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... aix6.1 ld.so
checking how to hardcode library paths into programs... immediate
checking for snappy_compress in -lsnappy... yes
configure: error: No support for this OS (aix6.1) yet
Bad exit status from /var/opt/freeware/tmp/rpm-tmp.28031 (%build)

I have referance issues #61  Can't compile on AIX 5.3 ,but,still has this problem.

**Comment by shaolila** [comment]
leveldb1.17    
On AIX 6.1 it does not compile.
The command line used is "make"

I added a few things, to try the compilation on AIX.
In build_detect_platform : 
AIX)
        PLATFORM=OS_AIX
        PLATFORM_CFLAGS="-pthread -DOS_AIX"
        PLATFORM_LDFLAGS="-lpthread"

There also a lot of warnings like this one during the build process : 
In file included from ./port/port.h:14:0,
                 from table/format.cc:8:
./port/port_posix.h:44:22: fatal error: endian.h: No such file or directory
   #include <endian.h>

I checked the directory , build_config.mk is generated:
bash-4.3# cat build_config.mk
SOURCES=db/builder.cc db/c.cc db/db_impl.cc db/db_iter.cc db/dbformat.cc db/filename.cc db/log_reader.cc db/log_writer.cc db/memtable.cc db/repair.cc db/table_cache.cc db/version_edit.cc db/version_set.cc db/write_batch.cc table/block.cc table/block_builder.cc table/filter_block.cc table/format.cc table/iterator.cc table/merger.cc table/table.cc table/table_builder.cc table/two_level_iterator.cc util/arena.cc util/bloom.cc util/cache.cc util/coding.cc util/comparator.cc util/crc32c.cc util/env.cc util/env_posix.cc util/filter_policy.cc util/hash.cc util/histogram.cc util/logging.cc util/options.cc util/status.cc  
MEMENV_SOURCES=helpers/memenv/memenv.cc
CC=cc
CXX=g++
PLATFORM=OS_AIX
PLATFORM_LDFLAGS=-lpthread
PLATFORM_LIBS= -lsnappy
PLATFORM_CCFLAGS=  -DLEVELDB_PLATFORM_POSIX -DSNAPPY
PLATFORM_CXXFLAGS=  -DLEVELDB_PLATFORM_POSIX -DSNAPPY
PLATFORM_SHARED_CFLAGS=-fPIC
PLATFORM_SHARED_EXT=so
PLATFORM_SHARED_LDFLAGS=-shared -Wl,-soname -Wl,
PLATFORM_SHARED_VERSIONED=true

 
it seems OS_AIX does not works.

then I modified ./port/port_posix.h as follow:
#elif defined(OS_AIX)
#include <sys/types.h>
#include <sys/param.h>
#else
 // #include <endian.h>
  #define PLATFORM_IS_LITTLE_ENDIAN false
  #include <sys/types.h>
  #include <sys/param.h>
#endif


then got the erros as follow:
bash-4.3# make
g++ -lpthread -shared -Wl,-soname -Wl,libleveldb.so.1 -I. -I./include -DLEVELDB_PLATFORM_POSIX -DSNAPPY -O2 -DNDEBUG        -fPIC db/builder.cc db/c.cc db/db_impl.cc db/db_iter.cc db/dbformat.cc db/filename.cc db/log_reader.cc db/log_writer.cc db/memtable.cc db/repair.cc db/table_cache.cc db/version_edit.cc db/version_set.cc db/write_batch.cc table/block.cc table/block_builder.cc table/filter_block.cc table/format.cc table/iterator.cc table/merger.cc table/table.cc table/table_builder.cc table/two_level_iterator.cc util/arena.cc util/bloom.cc util/cache.cc util/coding.cc util/comparator.cc util/crc32c.cc util/env.cc util/env_posix.cc util/filter_policy.cc util/hash.cc util/histogram.cc util/logging.cc util/options.cc util/status.cc   -o libleveldb.so.1.17 -lsnappy
util/env_posix.cc: In member function 'virtual leveldb::Status leveldb::{anonymous}::PosixSequentialFile::Read(size_t, leveldb::Slice*, char*)':
util/env_posix.cc:50:51: error: 'fread_unlocked' was not declared in this scope
     size_t r = fread_unlocked(scratch, 1, n, file_);
                                                   ^
util/env_posix.cc: In member function 'virtual leveldb::Status leveldb::{anonymous}::PosixWritableFile::Append(const leveldb::Slice&)':
util/env_posix.cc:195:66: error: 'fwrite_unlocked' was not declared in this scope
     size_t r = fwrite_unlocked(data.data(), 1, data.size(), file_);
                                                                  ^
util/env_posix.cc: In member function 'virtual leveldb::Status leveldb::{anonymous}::PosixWritableFile::Flush()':
util/env_posix.cc:212:30: error: 'fflush_unlocked' was not declared in this scope
     if (fflush_unlocked(file_) != 0) {
                              ^
util/env_posix.cc: In member function 'virtual leveldb::Status leveldb::{anonymous}::PosixWritableFile::Sync()':
util/env_posix.cc:251:30: error: 'fflush_unlocked' was not declared in this scope
     if (fflush_unlocked(file_) != 0 ||
                              ^
make: *** [libleveldb.so.1.17] Error 1


then I added a few things in ./port/port_posix.h:
#ifndef OS_AIX
#define OS_AIX
#endif

#if defined(OS_MACOSX) || defined(OS_SOLARIS) || defined(OS_FREEBSD) ||\
    defined(OS_NETBSD) || defined(OS_OPENBSD) || defined(OS_DRAGONFLYBSD) ||\
    defined(OS_ANDROID) || defined(OS_HPUX) || defined(OS_AIX)

finally it cames the error:

bash-4.3# make
g++ -lpthread -shared -Wl,-soname -Wl,libleveldb.so.1 -I. -I./include -DLEVELDB_PLATFORM_POSIX -DSNAPPY -O2 -DNDEBUG        -fPIC db/builder.cc db/c.cc db/db_impl.cc db/db_iter.cc db/dbformat.cc db/filename.cc db/log_reader.cc db/log_writer.cc db/memtable.cc db/repair.cc db/table_cache.cc db/version_edit.cc db/version_set.cc db/write_batch.cc table/block.cc table/block_builder.cc table/filter_block.cc table/format.cc table/iterator.cc table/merger.cc table/table.cc table/table_builder.cc table/two_level_iterator.cc util/arena.cc util/bloom.cc util/cache.cc util/coding.cc util/comparator.cc util/crc32c.cc util/env.cc util/env_posix.cc util/filter_policy.cc util/hash.cc util/histogram.cc util/logging.cc util/options.cc util/status.cc   -o libleveldb.so.1.17 -lsnappy
ld: 0706-005 Cannot find or open file: libleveldb.so.1
        ld:open(): A file or directory in the path name does not exist.
collect2: error: ld returned 255 exit status
make: *** [libleveldb.so.1.17] Error 1

**Comment by shaolila** [comment]
@cmumford  pls help me with this problem ,thank you .

**Comment by cmumford** [comment]
Hi @shaolila:

I'm really sorry, but AIX isn't a supported platform for leveldb. I don't have access to a machine running AIX to attempt to help out with this. Good luck with your porting effort. You may consider publishing your AIX port back to GitHub for others to use or contribute to.
