### ISSUE TITLE
Can't compile on OSX 10.5.8 + GCC 4.0.1

### ISSUE THREAD

**Issue by cmumford** [google/leveldb#16]
Original [issue 10](https://code.google.com/p/leveldb/issues/detail?id=10) created by voidptrptr on 2011-06-21T14:34:59.000Z:

<b>What steps will reproduce the problem?</b>

Can't compile on OSX

$ make
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG        db/table_cache.cc -o db/table_cache.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG        db/version_edit.cc -o db/version_edit.o
g++ -c -I. -I./include -DLEVELDB_PLATFORM_OSX -O2 -DNDEBUG        db/version_set.cc -o db/version_set.o
db/version_set.cc: In member function ‘void leveldb::VersionSet::Builder::Apply(leveldb::VersionEdit_)’:
./db/version_edit.h:99: error: ‘std::vector&lt;std::pair&lt;int, leveldb::InternalKey&gt;, std::allocator&lt;std::pair&lt;int, leveldb::InternalKey&gt; &gt; &gt; leveldb::VersionEdit::compact_pointers_’ is private
db/version_set.cc:287: error: within this context
./db/version_edit.h:99: error: ‘std::vector&lt;std::pair&lt;int, leveldb::InternalKey&gt;, std::allocator&lt;std::pair&lt;int, leveldb::InternalKey&gt; &gt; &gt; leveldb::VersionEdit::compact_pointers_’ is private
db/version_set.cc:288: error: within this context
./db/version_edit.h:99: error: ‘std::vector&lt;std::pair&lt;int, leveldb::InternalKey&gt;, std::allocator&lt;std::pair&lt;int, leveldb::InternalKey&gt; &gt; &gt; leveldb::VersionEdit::compact_pointers_’ is private
db/version_set.cc:290: error: within this context
./db/version_edit.h:86: error: ‘typedef class std::set&lt;std::pair&lt;int, uint64_t&gt;, std::less&lt;std::pair&lt;int, uint64_t&gt; &gt;, std::allocator&lt;std::pair&lt;int, uint64_t&gt; &gt; &gt; leveldb::VersionEdit::DeletedFileSet’ is private
db/version_set.cc:294: error: within this context
./db/version_edit.h:100: error: ‘std::set&lt;std::pair&lt;int, uint64_t&gt;, std::less&lt;std::pair&lt;int, uint64_t&gt; &gt;, std::allocator&lt;std::pair&lt;int, uint64_t&gt; &gt; &gt; leveldb::VersionEdit::deleted_files_’ is private
db/version_set.cc:294: error: within this context
./db/version_edit.h:101: error: ‘std::vector&lt;std::pair&lt;int, leveldb::FileMetaData&gt;, std::allocator&lt;std::pair&lt;int, leveldb::FileMetaData&gt; &gt; &gt; leveldb::VersionEdit::new_files_’ is private
db/version_set.cc:304: error: within this context
./db/version_edit.h:101: error: ‘std::vector&lt;std::pair&lt;int, leveldb::FileMetaData&gt;, std::allocator&lt;std::pair&lt;int, leveldb::FileMetaData&gt; &gt; &gt; leveldb::VersionEdit::new_files_’ is private
db/version_set.cc:305: error: within this context
./db/version_edit.h:101: error: ‘std::vector&lt;std::pair&lt;int, leveldb::FileMetaData&gt;, std::allocator&lt;std::pair&lt;int, leveldb::FileMetaData&gt; &gt; &gt; leveldb::VersionEdit::new_files_’ is private
db/version_set.cc:306: error: within this context
db/version_set.cc: In member function ‘void leveldb::VersionSet::Builder::SaveTo(leveldb::Version_)’:
./db/version_set.h:66: error: ‘std::vector&lt;leveldb::FileMetaData_, std::allocator&lt;leveldb::FileMetaData_&gt; &gt; leveldb::Version::files_ [7]’ is private
db/version_set.cc:320: error: within this context
./db/version_set.h:66: error: ‘std::vector&lt;leveldb::FileMetaData_, std::allocator&lt;leveldb::FileMetaData_&gt; &gt; leveldb::Version::files_ [7]’ is private
db/version_set.cc:324: error: within this context
db/version_set.cc: In member function ‘void leveldb::VersionSet::Builder::MaybeAddFile(leveldb::Version_, int, leveldb::FileMetaData_)’:
./db/version_set.h:66: error: ‘std::vector&lt;leveldb::FileMetaData_, std::allocator&lt;leveldb::FileMetaData_&gt; &gt; leveldb::Version::files_ [7]’ is private
db/version_set.cc:367: error: within this context
make: **\* [db/version_set.o] Error 1

<b>What version of the product are you using? On what operating system?</b>

from SVN

<b>Please provide any additional information below.</b>

gcc --version
i686-apple-darwin9-gcc-4.0.1 (GCC) 4.0.1 (Apple Inc. build 5488)
Copyright (C) 2005 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by springbloom2018** [comment]
Thank  you. I try to found it..
